name: Update Packagist

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  packagist:
    runs-on: ubuntu-latest
    
    steps:
      - name: Update Packagist
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"repository":{"url":"https://github.com/idpcks/laravelwudel_notif"}}' \
            https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_API_TOKEN }}
        env:
          PACKAGIST_USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
          PACKAGIST_API_TOKEN: ${{ secrets.PACKAGIST_API_TOKEN }}
